version: '2.4'

volumes:
  common_shared:

services:

  irisdriveservice:
    image: mhorita/iris-drive-demo
    container_name: iris-drive-demo
    hostname: irisdriveservice
    restart: on-failure
    ports:
    - "51003:51773"
    - "52003:52773"
    volumes:
    - ${PWD}/IRIS-MQTT/projects:/projects
                                             
    networks:
    - mqttnw

  mqttbroker:
    #build: 
    #  context: ./MQTTBroker
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mqttbroker
    restart: on-failure
    expose:
    - 1883
    - 9001
    ports:
    - 1883:1883
    - 9001:9001
    volumes:
    - ${PWD}/MQTTBroker/conf:/mosquitto/config
    - ${PWD}/MQTTBroker/data:/mosquitto/data
    - ${PWD}/MQTTBroker/log:/mosquitto/log
    networks:
    - mqttnw

networks:
  mqttnw:
    driver: bridge
