FROM python:3.7.4

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

RUN pip install --upgrade pip && pip install --upgrade paho-mqtt && pip install --upgrade numpy && pip install --upgrade pandas

